### ISSUE TITLE
Performance Issues when Timer stopped?

### ISSUE THREAD

**Issue by flixius** [envynoiz/countimer#4]
Hello,

At first thanks for your great plugin! I have no real issue to report but just a quick question if I have to care about created instances I won't use in the future.

Here the workflow: 

```
$('.myclass').countimer({myparams}); <- start a timer 
//later... 
$('.myclass').countimer('stop'); 
$('.myclass').remove(); 
// ^ is the instance in the plugin still alive in this case?

^ if yes... could it lead in performance issues even the instance is doing nothing (because stopped)? except existing :)

I am asking because i will instanciate thousands of timers and remove them after a short time like i showed in the code above.

**Comment by envynoiz** [comment]
Hello @flixius,

Just to let you know, today I added a new version that includes the "**destroy**" method for the plugin. You can use it in order to remove in a proper way, the instance and all the attached events on it. With that you should not worry about the performance.

Here a sample how to use it:

`$('.timer').countimer('destroy');`

Also you can decide whether to use the option **destroyDOMElement** or not when the plugin is destroyed. If you set it in true, the DOM element will be destroyed along with the plugin instance.

Please feel free to check it out so, you can let me know if it is necessary something additional.

Regards.

**Comment by flixius** [comment]
Hey @envynoiz  
Thank you very much! I tested it and it works perfectly. 

One "nice to have" would be not to throw an Exception when "destroy" is called and there's no instance (Uncaught Error: countimer is not instantiated yet). But I solved it by adding a "HasInstance" method in your code and so i check it before i call destroy. 

PS: Do you have PayPal? I would like to make a little donation to appreciate your work.

**Comment by envynoiz** [comment]
Sorry for the late response I completely forgot to answer your comment. Yeah, I can try to add that "nice to have" later but for now, I will close this issue since the destroy method is working as expected.

PS: yeah I have PayPal account but no worries man hehe, I really appreciate you got the library :D
